function [ cDiagnostics, iHMMused ] = selectModel(iPeriod, cSettings, iNobs, cHMM, cDiagnostics )
%selectModel selects HMM that best fits the given data
%
%   * calculates AIC and BIC                   
%   * selects HMM that best fits the given data based on settings
%
%   Input:
%   iPeriod:        number of rolling period that called the function
%   cSettings:      structure of settings, as specified in Runtime.m
%   iNobs:          number of observations
%   cHMM:           structure of HMMs, generated by calibrateHMM
%   cDiagnostics:   structure of diagnostic summary statistics  
%
%   Output:
%   cDiagnostics:   structure of diagnostic summary statistics 
%   iHMMused:       index of selected HMM in cHMM

%% Calculate Information Criteria
 [cDiagnostics(iPeriod).AICWeights(1:length(cSettings.NoStates),1), cDiagnostics(iPeriod).BICProb(1:length(cSettings.NoStates),1)] = calcInfCriteria(abs([cHMM.LogLik]), [cHMM.NoParameters], iNobs); 
    
 %% Select Model
 if strcmp(cSettings.ModelSelCriteria,'AIC')
        [~, iHMMused] = max(cDiagnostics(iPeriod).AICWeights(:,1));
    elseif strcmp(cSettings.ModelSelCriteria,'BIC')
        [~, iHMMused] = max(cDiagnostics(iPeriod).BICProb(:,1));
    else
        error('cSettings.ModelSelCriteria not initialised properly!')
    end
    cDiagnostics(iPeriod).NoStates = cHMM(iHMMused).NoStates;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% This source code is part of RSMentalAccounting.
%
% Copyright(c) 2014 Felix Andresen
% All Rights Reserved.
%
% This program shall not be used, rewritten, or adapted as the basis of a commercial software
% or hardware product without first obtaining written permission of the author. The author make
% no representations about the suitability of this software for any purpose. It is provided
% "as is" without express or implied warranty.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Written by
%   Felix Andresen  
%   Master Thesis:  Regime Switching Models and the Mental Accounting Framework
%   Advisors:       Prof. Jan Vecer, Prof. Sebastien Lleo
%   Master of Science in Quantitative Finance, Frankfurt School of Finance and Management
%   Frankfurt am Main, Germany
%   02/2014
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Contact
%   E-mail: Felix.Andresen@gmail.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%